Refactor the default selection
uhh-cms/hh2bbtautau pull request #13
Opened 2024-02-13 15:34 UTC by haddadanas

This PR improves the following on the code in the `default.py` in the selection:

- Refactor the code parts in the `default` selector into `particle_selection`, `mc_selection` and `selection_mc_weights` for better maintainability and convenience when creating or modifying a selector
- Added a new `empty` selector, which creates all columns added in the `default` selector, but returns an all True mask

The results of the refactored selector was compared with results of the original one for the dataset `data_mu_e`.

2024-06-18 12:07 UTC, nprouvost requested changes

2024-06-18 12:07 UTC, nprouvost commented on hbt/selection/default.py
> +    events = self[process_ids](events, **kwargs)
not a new selection, so this should probably be in the main Selectors (default and "empty"), instead of here

2024-06-19 10:40 UTC, haddadanas commented on hbt/selection/default.py
> +def empty(
Back then I didn't know about the empty cf selector or it hasn't existed yet.
I assume this is then not needed and can be removed then or?

2024-06-19 10:53 UTC, haddadanas commented on hbt/selection/default.py
> +def mc_selection(
I understand, but wouldn't we have then a mix between the selection and production modules?

2024-06-21 08:22 UTC, riga commented on hbt/selection/default.py
> +def mc_selection(
This wouldn't be a problem. In fact, that's actually desired :)

2024-07-23 13:44 UTC, closed without merging

2024-07-23 13:51 UTC, riga commented
Closed after private discussion.