Run 3 Analysis Setup
uhh-cms/hh2bbtautau pull request #19
Opened 2024-06-03 11:49 UTC by haddadanas

This PR adds the configuration files for run 3 and adjusts some functions of the analysis for it :partying_face: 

New:
- New Correction files
- Separate tau trigger from tau correction factors
- Adjusted the input parameters of the `correctionlib`
-  Added new 2022 Triggers and adjusted the analysis for the new cross `tau-tau-jet` trigger
- Added new Triggers for 2023 (however not tested yet)
- Refactor all working points into the config files

2024-06-03 17:30 UTC, riga requested changes
Awesome work!
I just have a handful of inline comments that should be easy to adapt, but we can also discuss them in person.
🎉

2024-06-03 17:30 UTC, riga commented on hbt/calibration/default.py
> +        print("met_phi_setup will be skipped for now, since correction files for run 3 are not yet available!")
We can drop this case as there will likely be no met phi correction.

2024-06-03 17:30 UTC, riga commented on hbt/config/configs_run2ul.py
> +    cfg.add_tag("run2")
There is an aux field "run" now directly on the campaign that we should use.

2024-06-03 17:30 UTC, riga commented on hbt/production/tau.py
> +    if self.config_inst.has_tag("run3"):
Should use the "run" aux entry of the campaign.

2024-06-03 17:43 UTC, riga requested changes
Forgot to review the config itself ... super impressive.

2024-06-03 17:43 UTC, riga commented on hbt/config/configs_run3.py
> +    postfixEE = f"{campaign.x.postfix}EE"
`postfix_ee`

2024-06-03 17:43 UTC, riga commented on hbt/config/configs_run3.py
> +    cfg.add_tag("run3")
We can skip this when we use the campaigns' "run" aux field.

2024-06-03 17:43 UTC, riga commented on hbt/config/configs_run3.py
> +
We can remove these lines.

2024-06-03 17:43 UTC, riga commented on hbt/config/configs_run3.py
> +    cfg.x.tau_tagger = "DeepTau2018v2p5"  # "DeepTauv2p5"
We can remove the comment :)

2024-06-03 17:43 UTC, riga commented on hbt/config/configs_run3.py
> +    # cfg.x.met_phi_correction_set = "{variable}_metphicorr_pfmet_{data_source}"
Can also be removed.

2024-06-03 17:43 UTC, riga commented on hbt/config/configs_run3.py
> +    json_mirror_alt = "/afs/cern.ch/user/a/anhaddad/public/jsonpog_alt"
`json_mirror = "/afs/cern.ch/user/m/mrieger/public/mirrors/jsonpog-integration-7d9636bf"`
:)

Then we can also change `json_mirror_alt` to `json_mirror` below.

2024-06-03 17:43 UTC, riga commented on hbt/config/configs_run3.py
> +    else:  # year 2023
Explicit `elif year == 2023` would be better here.

2024-06-03 17:56 UTC, pkausw requested changes
Thanks for all the work @haddadanas ! Just some minor comments from my side

2024-06-03 22:16 UTC, haddadanas commented on hbt/config/configs_run3.py
> +    json_mirror_alt = "/afs/cern.ch/user/a/anhaddad/public/jsonpog_alt"
sure, we can do it tomorrow

2024-06-03 22:19 UTC, haddadanas commented
Thank you @riga and @pkausw for the feedback! 
I corrected most of it, but there are still some unresolved conversations, which I'd like to discuss with you in person :)

2024-06-04 21:08 UTC, haddadanas commented
Done :heavy_check_mark: 
Well almost. Only thing missing is to replace the link of `json_mirror_alt`  to a link on Marcel's afs (I left the comment unresolved)

2024-06-05 09:28 UTC, riga commented on hbt/config/configs_run3.py
> +    json_mirror_alt = "/afs/cern.ch/user/a/anhaddad/public/jsonpog_alt"
You can change this to `/afs/cern.ch/work/m/mrieger/public/mirrors/jsonpog-integration-taupog`, I copied your directory there.

2024-06-05 12:52 UTC, riga approved these changes

2024-06-05 12:52 UTC, merged