run 2 updates
uhh-cms/hh2bbtautau pull request #22
Opened 2024-06-06 15:37 UTC by nprouvost

2024-06-07 08:00 UTC, riga requested changes
Nice work @aalvesan and @nprouvost !

I had a couple minor comments that I made inline below.

Besides that, I'd like to suggest to move all inference related changes to a second PR. The code is essentially a drop-in from the hbw analysis but I think we should discuss their approaches first and see if they apply to our analysis.

2024-06-10 11:35 UTC, nprouvost commented on hbt/calibration/default.py
> +    return events
removed

2024-06-10 11:36 UTC, nprouvost commented on hbt/calibration/placeholder.py
> +# coding: utf-8
changed

2024-06-10 11:36 UTC, nprouvost commented on hbt/config/variables.py
> +        name="diTau_mass",
changed

2024-06-10 11:36 UTC, nprouvost commented on hbt/production/empty.py
> +# from hbt.production.tau import tau_weights, trigger_weights
removed

2024-06-10 11:36 UTC, nprouvost commented on hbt/production/empty.py
> +# coding: utf-8
changed

2024-06-10 11:36 UTC, nprouvost commented on hbt/selection/empty.py
> +# coding: utf-8
removed

2024-06-10 11:36 UTC, nprouvost commented on hbt/production/hh_mass.py
> +        # events = self[normalized_btag_weights](events, **kwargs)
Solved by using option 2: removing these weights from this producer, both producers should be used at once

2024-06-10 11:47 UTC, nprouvost commented on hbt/selection/trigger.py
> +
removed

2024-06-11 16:59 UTC, riga approved these changes

2024-06-11 17:00 UTC, merged