Add task to create csv file for syncronization tasks
uhh-cms/hh2bbtautau pull request #41
Opened 2024-10-24 11:29 UTC by Bogdan-Wiederspan

This PR will add a task called CreateSyncFile, which creates for given columns and mapping scheme a csv file necessary to use synchronization tools.

This PR comes in a 2-step process:
Part 1: Add task structure to generally create the csv file from existing columns
Part 2: add structure to handle selection masks and also save them within a csv

2024-10-24 14:05 UTC, riga requested changes
Some minor changes.
Let's discuss details on the task implementation in person.

2024-10-24 14:11 UTC, Bogdan-Wiederspan commented on hbt/tasks/sync_csv.py
> +)
what about check_overlap_task right below?

2024-10-24 14:11 UTC, Bogdan-Wiederspan commented on hbt/tasks/sync_csv.py
> +
done, im starting to think that i use flake8 wrong^^

2024-10-24 14:19 UTC, riga commented on hbt/tasks/sync_csv.py
> +)
This check is input related and should / can run.

2024-10-24 14:28 UTC, Bogdan-Wiederspan commented on hbt/tasks/sync_csv.py
> +)
ok, is done.

2024-10-25 12:19 UTC, riga approved these changes

2024-10-25 12:20 UTC, merged