Trigger sf
uhh-cms/hh2bbtautau pull request #48
Opened 2024-11-15 16:38 UTC by nprouvost

Add trigger scale factors for run3 etau and mutau channel and create conventions for trigger config

Milestones:

- [ ] Create conventions for trigger ids and apply them to all years 
- [ ] Add all efficiencies (e, mu, tau, single and cross triggers, data and mc) as producers
- [ ] Define calculation of trigger SF from efficiencies 
- [ ] use all efficiencies to calculate trigger SF
- [ ] add corresponding SF configs to analysis config
- [ ] Update default producer accordingly
- [ ] check usage of event mask in muon_weight derived producer
- [ ] if necessary: change masks to object masks and update rest of code accordingly

2025-03-31 08:32 UTC, riga requested changes
Hey @nprouvost, this looks like a huge effort, thanks! 🙏

Let's split the review into two parts. For the first part I had some coding / cf-related comments inline. For the second part I think we need to discuss the three main changes (and `selection/jet.py`, `selection/lepton.py`, and `production/trigger_sf.py`) in person.

2025-03-31 14:00 UTC, riga commented on hbt/config/configs_hbt.py
>          json_mirror = "/afs/cern.ch/user/m/mrieger/public/mirrors/jsonpog-integration-377439e8"
Update: no need to do that after you merged the target branch back in.

2025-04-11 17:05 UTC, nprouvost commented on hbt/config/configs_hbt.py
> +        cfg.x.electron_trigger_sf_names = ElectronSFConfig(
done for all below, for this specific one I can't, it comes from columnflow. Or we change it in columnflow too

2025-04-11 17:05 UTC, nprouvost commented on hbt/config/configs_hbt.py
> +        cfg.x.muon_trigger_sf_names = MuonSFConfig(
Same as above for electron configs.

2025-04-14 10:52 UTC, nprouvost commented on hbt/production/trigger_sf.py
> +    # nan happens for all events not in etau, due to efficiency == 0
no it's outdated, this function is used several times, once for all channels where an "OR" must be performed. Each time it is used, all events that are not in the specific channel return nan, due to the MC efficiency calculation returning 0. So we replace it with 1.0 as no change should happen for these events due to the specific channel. The comment with etau is simply because it was at first only implemented in etau. I will remove it

2025-04-14 15:51 UTC, nprouvost commented on hbt/production/trigger_sf.py
> +    # nan happens for all events not in etau, due to efficiency == 0
done

2025-04-15 13:42 UTC, nprouvost commented on hbt/production/tau.py
> +        tau_dm10_mask = tau_mask & ((dm == 10) | (dm == 11))  # why both in one?
systematics for dm11 added

2025-04-17 06:38 UTC, riga requested changes

2025-04-17 06:38 UTC, riga commented on hbt/production/tau.py
> +                reduce_mul(sf_nom),
Correct to store the product here?
Same below for the variations.

2025-04-17 06:38 UTC, riga commented on hbt/production/tau.py
> +                    flat_decay_mode_mask = flat_np_view(decay_mode_mask, axis=1)
Could you make the `direction` loop the inner-most one, starting below `flat_decay_mode_mask = ...`? Then we can half the number of times we create the joined mask.

2025-04-17 07:31 UTC, nprouvost commented on hbt/production/tau.py
> +                reduce_mul(sf_nom),
We could do it in trigger_sf instead, but don't need to as we always need to multiply them anyway...

2025-04-23 07:51 UTC, nprouvost commented on hbt/production/trigger_sf.py
> +        (ak.local_index(events.Electron.pt) == 0)
as discussed, we will not change it for now as we want object-level masks for the columnflow producers, but it might be a good idea for future changes, as ak.local_index creates copies of arrays

2025-04-23 07:52 UTC, nprouvost commented on hbt/production/trigger_sf.py
> +) -> ak.Array:
done

2025-04-25 08:12 UTC, riga approved these changes
💯

2025-04-25 08:13 UTC, merged