Sync updates
uhh-cms/hh2bbtautau pull request #52
Opened 2024-12-10 10:26 UTC by riga

*tba*

---

## Open items

- [ ] Add custom METFilter for broken data eras in 22 (@riga)
- [ ] Switch to PuppiMET (@haddadanas)
- [ ] For tau-tau-jet trigger, check effect of the two hhbjet matching strategies, potentially following up with cclub (@aalvesan)
- [ ] review sync_updates branch (@riga, @pkausw)

2025-01-09 16:06 UTC, nprouvost requested changes
my comments up to default selection (I did not review the files I changed myself...)

2025-01-10 07:31 UTC, riga reviewed
LGTM!

2025-01-10 11:27 UTC, Bogdan-Wiederspan commented on hbt/selection/lepton.py
> -            # ((mva_noniso_wp90 == 1) & (events.Electron.pfRelIso03_all < 0.3))
is there a reason why we don't use the isolation score for electron?

2025-01-10 11:33 UTC, Bogdan-Wiederspan commented on hbt/selection/lepton.py
> -    TODO: there is no decay mode selection yet, but this should be revisited!
i guess we dropped the "decay mode selection"?

2025-01-10 14:33 UTC, nprouvost commented on hbt/selection/lepton.py
> +    leading_taus = events.Tau[:, :0]
That's the whole point! these are the default arrays before being updated below

2025-01-10 14:47 UTC, nprouvost approved these changes
LGTM

2025-01-10 14:48 UTC, Bogdan-Wiederspan commented on hbt/selection/lepton.py
> -            # ((mva_noniso_wp90 == 1) & (events.Electron.pfRelIso03_all < 0.3))
After talking to Marcel: The reason why we don't use this line anymore is that `mva_iso_wp90` is combines both noniso with relIso information.

2025-01-10 14:48 UTC, Bogdan-Wiederspan commented on hbt/selection/lepton.py
> +    leading_taus = events.Tau[:, :0]
Thank for explaining, makes sense.

2025-01-10 14:49 UTC, Bogdan-Wiederspan commented on hbt/selection/lepton.py
Looks good to me.

2025-01-10 14:50 UTC, Bogdan-Wiederspan commented on hbt/selection/trigger.py
Nice, trigger legs are much more readable by just using the name.

2025-01-10 15:29 UTC, Bogdan-Wiederspan commented on hbt/config/triggers.py
> +        "VBFpDoublePFTau_run3": Bits(v12=4096),  # warning: this trigger bit expects "ChargedIso" in the filter name, this does not correspond to our actual VBF filter name  # noqa
Would it be a good idea to have a mapping for this kind of case or should we rename our filter names?

2025-01-10 15:39 UTC, Bogdan-Wiederspan commented on hbt/config/triggers.py
> +        "VBFpDoublePFTau_run3": Bits(v12=4096),  # warning: this trigger bit expects "ChargedIso" in the filter name, this does not correspond to our actual VBF filter name  # noqa
There was a misunderstanding and Nathan explained to me that this is a wrong doing by the guys that wrote the triggers in CMSSW and that a mapping would not solve the problem.

2025-01-13 08:50 UTC, riga commented on hbt/config/triggers.py
> +                        # "Tight" if nano_version == 14 else None,
@nprouvost "Tight" does not exist for the "e" leg. I commented this out to run tests, but can you fix this and uncomment again?

2025-01-13 12:07 UTC, Bogdan-Wiederspan commented on hbt/production/btag.py
> +    reqs["selection_stats"] = MergeSelectionStats.req_different_branching(
What exactly does ´req_different_branching´ does? I can't find the symbols definition.

2025-01-13 13:25 UTC, Bogdan-Wiederspan commented on hbt/config/configs_hbt.py
> +            # "dy_m50toinf_0j", "dy_m50toinf_1j", "dy_m50toinf_2j",
I was just wondering why ´dy_m50toinf_0j´ is commented out.

2025-01-13 17:50 UTC, pkausw reviewed
First set of comments

2025-01-13 17:50 UTC, pkausw commented on hbt/production/btag.py
> +    return
which stats fields are we talking about?

2025-01-15 18:48 UTC, riga commented on hbt/config/configs_hbt.py
> +            # "dy_m50toinf_0j", "dy_m50toinf_1j", "dy_m50toinf_2j",
Added again by @pkausw

2025-01-15 18:49 UTC, riga commented on hbt/production/btag.py
> +    reqs["selection_stats"] = MergeSelectionStats.req_different_branching(
It does exactly the same as `TaskClass.req(task_instance)` does, but it skips parameters from the intersection between `TaskClass` and `task_instance` that would imply an equal branching -> it skips "branches", "acceptance", "tolerance" and "pilot".

2025-01-15 18:52 UTC, riga commented on hbt/config/configs_hbt.py
> +            # "dy_m4to10", "dy_m10to50", "dy_m50toinf",
Added by you in f555b14 ;)

2025-01-15 18:53 UTC, riga commented on hbt/config/configs_hbt.py
> +                    procs.n.w_lnu_ge3j,
I added that one in a cmsdb commit.

2025-01-15 18:53 UTC, riga commented on hbt/production/btag.py
> +    return
This was one of the hacks I was talking about. I removed it again from the branch.

2025-01-15 18:56 UTC, riga commented on hbt/config/categories.py
> +        "sign": [config.get_category("os")],
Added back in f6247eaf.

2025-01-16 11:41 UTC, nprouvost commented on hbt/config/triggers.py
> +                        # "Tight" if nano_version == 14 else None,
sorry already fixed in 2022, but forgot to fix that in 2023, now done

2025-01-16 12:50 UTC, merged